name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=20.3.3
  - pip:
      - pandas==1.5.2
      - wandb==0.13.7
      - jupyterlab==3.5.0
      - seaborn==0.11.1
      - pandas-profiling==3.4.0
      - pyarrow==10.0.0
      - ipywidgets==8.0.4