name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=20.3.3
  - pip:
      - wandb==0.13.5
      - mlflow==2.0.1
      - pyyaml==5.3.1
      - hydra-core==1.0.6