name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=20.3.3
  - pip:
      - pandas==1.5.2
      - wandb==0.13.7
      - mlflow==2.0.1
      - scikit-learn==1.2.0
      - matplotlib==3.3.4
      - pillow==9.3.0
