name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=20.3.3
  - pip:
      - requests==2.24.0
      - wandb==0.13.7
      - mlflow==2.0.1
      - git+https://github.com/ngocpc/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
